### ISSUE TITLE
torch.AcceleratorError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by xiaoyang212** [RManLuo/gfm-rag#24]
<img width="1503" height="168" alt="Image" src="https://github.com/user-attachments/assets/9f660f42-fa4a-4787-b2a0-74f643825806" />
Hello author, I have recently been trying to reproduce your excellent work, but I encountered the problem shown in the image during the stage 2 pre-training phase. My device is an RTX4090 with CUDA 13.0

**Comment by RManLuo** [comment]
Hi, thanks for your question. Please try downgrading to CUDA 12 and provide more details about the error message to help us identify the issue.

**Comment by xiaoyang212** [comment]
Thank you for your reply，the problem has been solved.



---- Replied Message ----
| From | Linhao ***@***.***> |
| Date | 11/20/2025 09:47 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [RManLuo/gfm-rag] torch.AcceleratorError: CUDA error: an illegal memory access was encountered (Issue #24) |
RManLuo left a comment (RManLuo/gfm-rag#24)

Hi, thanks for your question. Please try downgrading to CUDA 12 and provide more details about the error message to help us identify the issue.
